In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)
print(torch.cuda.is_available())

2.1.1+cu121
True


In [2]:
!nvidia-smi

Mon Dec 11 09:41:38 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650        Off | 00000000:01:00.0  On |                  N/A |
| N/A   31C    P8               4W /  30W |     57MiB /  4096MiB |     33%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
print(scalar.ndim)
print(scalar.shape)

0
torch.Size([])


In [5]:
vector = torch.Tensor([1, 2])
vector

tensor([1., 2.])

In [6]:
print(vector.ndim)
print(vector.shape)
print(vector[0])

1
torch.Size([2])
tensor(1.)


In [7]:
MATRIX = torch.Tensor([[1, 2],
                        [3, 4]])
MATRIX

tensor([[1., 2.],
        [3., 4.]])

In [8]:
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX[0][0])
print(MATRIX[0][1])
print(MATRIX[1][0])
print(MATRIX[1][1])

2
torch.Size([2, 2])
tensor([1., 2.])
tensor([3., 4.])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)


In [14]:
TENSOR = torch.Tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [17]:
print(TENSOR.ndim)
print(TENSOR.shape)
TENSOR[0]

3
torch.Size([1, 3, 3])


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [19]:
TENSOR_1=torch.Tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                        
                        [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR_1

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [22]:
print(TENSOR_1.ndim)
print(TENSOR_1.shape)
TENSOR_1[0][1][0].item()

3
torch.Size([2, 3, 3])


4.0

In [23]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6175, 0.3900, 0.3600, 0.7392],
        [0.7788, 0.1154, 0.1396, 0.6230],
        [0.8762, 0.5346, 0.3853, 0.5064]])

In [25]:
print(random_tensor.shape)
print(random_tensor.ndim)

torch.Size([3, 4])
2


In [29]:
# Create a random tensor with shape and size similar to an image tensor
random_tensor_img = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
print(random_tensor_img)
random_tensor_img.shape, random_tensor_img.ndim

tensor([[[0.8982, 0.6985, 0.7941,  ..., 0.4414, 0.1025, 0.8451],
         [0.5957, 0.1232, 0.1887,  ..., 0.4436, 0.5396, 0.5699],
         [0.7078, 0.0597, 0.1106,  ..., 0.7648, 0.7728, 0.5275],
         ...,
         [0.6386, 0.2751, 0.6854,  ..., 0.7339, 0.8445, 0.5083],
         [0.5640, 0.6082, 0.2504,  ..., 0.9458, 0.3811, 0.8658],
         [0.9475, 0.7375, 0.9818,  ..., 0.6066, 0.7542, 0.0309]],

        [[0.9082, 0.2724, 0.8868,  ..., 0.4590, 0.2817, 0.2701],
         [0.6422, 0.3651, 0.0660,  ..., 0.8392, 0.4964, 0.9191],
         [0.1924, 0.3943, 0.8919,  ..., 0.7585, 0.9051, 0.6135],
         ...,
         [0.1917, 0.9850, 0.8892,  ..., 0.1825, 0.3793, 0.5457],
         [0.0647, 0.1415, 0.5488,  ..., 0.6617, 0.1713, 0.5330],
         [0.7748, 0.7496, 0.5646,  ..., 0.3023, 0.7058, 0.3503]],

        [[0.4359, 0.9072, 0.9155,  ..., 0.2560, 0.3209, 0.3183],
         [0.5956, 0.5397, 0.3473,  ..., 0.9070, 0.5953, 0.9151],
         [0.4836, 0.5107, 0.9173,  ..., 0.7513, 0.0521, 0.

(torch.Size([3, 224, 224]), 3)

In [5]:
tensor_zeros =  torch.zeros(size=(3, 4))
print(tensor_zeros)
tensor_zeros.dtype

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


torch.float32

In [6]:
tensor_ones = torch.ones(size=(3, 4))
print(tensor_ones)
tensor_ones.dtype

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


torch.float32

In [8]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# one_to_thousand = torch.arange(start=0, stop=1000, step=77)
one_to_thousand = torch.arange(0, 1000, 77)
one_to_thousand

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [16]:
ten_zeros = torch.zeros_like(one_to_thousand)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
# float32_tensor = torch.tensor([1, 2, 3, 4],dtype=None)
float32_tensor = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
float32_tensor.dtype

torch.float32

In [26]:
float64_tensor = torch.tensor([1, 2, 3, 4],dtype=None)
float64_tensor.dtype

torch.int64

In [32]:
new_tensor = torch.Tensor([1, 2, 3, 4])
print(new_tensor)
new_tensor.dtype

tensor([1., 2., 3., 4.])


torch.float32

In [5]:
data = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=None)
float32_tensor = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9.0],dtype=None,
                                                            device=None,
                                                            requires_grad=False)
print(data.dtype)
float32_tensor.dtype

torch.int64


torch.float32

In [39]:
print(data)
print(float32_tensor)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [40]:
float16_tensor = float32_tensor.type(torch.float16)
print(float16_tensor)
float16_tensor.dtype

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)


torch.float16

In [43]:
float16_tensor * float32_tensor

tensor([ 1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [7]:
int_32_tensor =  torch.tensor([3, 6, 7, 8, 9, 10, 6, 7, 9], dtype=torch.long)
int_32_tensor

tensor([ 3,  6,  7,  8,  9, 10,  6,  7,  9])

In [8]:
float32_tensor * int_32_tensor

tensor([ 3., 12., 21., 32., 45., 60., 42., 56., 81.])

In [9]:
# Tensor DataType, Tensor Shape, Tensor Device
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5044, 0.6956, 0.2628, 0.5661],
        [0.4694, 0.1677, 0.1731, 0.9940],
        [0.8804, 0.4720, 0.7988, 0.9498]])

In [13]:
# Both size and shape can be used. They serve the same purpose.
# However, size is a function therefore needs parentheses at the end.
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [14]:
# Details about some tensor
print(some_tensor)
print(f"The DataType of Tensor: {some_tensor.dtype}")
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Device Tensor is on: {some_tensor.device}")

tensor([[0.5044, 0.6956, 0.2628, 0.5661],
        [0.4694, 0.1677, 0.1731, 0.9940],
        [0.8804, 0.4720, 0.7988, 0.9498]])
The DataType of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device Tensor is on: cpu


# Manipulating Tensors, (Tensors Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (Element Wise)
* Division
* Matrix Multiplication

In [10]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [11]:
tensor * 10

tensor([10, 20, 30])

In [12]:
tensor

tensor([1, 2, 3])

In [13]:
tensor - 10

tensor([-9, -8, -7])

In [14]:
# Try out Pytorch built-in functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [15]:
torch.add(tensor, 10)

tensor([11, 12, 13])

# Element wise multiplication

In [16]:
# Element wise multiplication
print(tensor, "*", tensor)
print("Equals", tensor*tensor)


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


# Matrix Multiplication
Matrix Multiplication or Dot Product is the most common operation in Deep Learning and hence needs to be practiced.

In [17]:
# PyTorch does Matrix Multiplication using torch.matmul() method.
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [20]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 8.11 ms, sys: 153 µs, total: 8.27 ms
Wall time: 5.89 ms


In [21]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 913 µs, sys: 0 ns, total: 913 µs
Wall time: 762 µs


tensor(14)

In [25]:
### One of the most common errors in Deep Learning is Shape Errors.
# The inner dimensions must match and the output dimensions would be the outer dimensions
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))
             

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [26]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.7062, 0.2411],
        [0.8277, 0.3925]])

In [27]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.7440, 0.7900, 1.0276],
        [0.4517, 0.4180, 0.7714],
        [0.4965, 0.5191, 0.7049]])

In [28]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3))

tensor([[1.9873, 1.2860, 2.3825],
        [2.8883, 2.4283, 3.6736],
        [2.9115, 2.8357, 3.1512]])

In [30]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 6))

tensor([[2.4371, 1.9637, 1.5490, 1.2314, 1.8869, 2.5523],
        [1.6154, 1.3741, 1.9780, 1.1912, 1.7695, 2.9945],
        [1.6885, 1.6513, 1.6402, 0.9289, 1.9685, 2.7522]])

In [24]:
tensor @ tensor # The @ symbol is used for tensor multiplication in Pytorch

tensor(14)

In [31]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is an alias for torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [32]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

## Matrix Transpose
There seems to be issue with the tnesor shapes, in order to fix the issues, we can use a **transpose** operation.

A **transpose** operation switches the axes of the matrix/tensor

In [35]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [36]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [38]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [39]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [52]:
print(f"Original Shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape}  <- Inner Dimenstions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput Shape: {output.shape}")
print("The tensor operations work after taking the transpose of tensor_B")

Original Shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3])  <- Inner Dimenstions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output Shape: torch.Size([3, 3])
The tensor operations work after taking the transpose of tensor_B


## Finding the min, max, mean, sum, etc (tensor aggregation)


In [61]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [57]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [56]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [67]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
x_float = x.type(torch.float32)
torch.mean(x_float), x_float.mean()

(tensor(45.), tensor(45.))

In [68]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [73]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [72]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape.
* View - return a view of the input tensor of certain shape but keep the same memort as the orginal tensor.

In [1]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [3]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [4]:
# Add an extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [5]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [6]:
# Changing z changes x because a view of a tensor shares the same memory as the original tensor.
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [7]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [8]:
x_vstacked = torch.vstack([x, x, x, x])
x_vstacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [9]:
x_hstacked = torch.hstack([x, x, x, x])
x_hstacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
print(x_reshaped)
x_reshaped.shape

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


torch.Size([9, 1])

In [11]:
print(x_reshaped.squeeze())
x_reshaped.squeeze().shape

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


torch.Size([9])

In [12]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove the extra dimensions from the x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [102]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous Target: {x_squeezed}")
print(f"Previous Shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous Target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [2]:
import torch
# torch.permute() - rearranges the dimensions of the tensors in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [Height, Width, color_channel]

# permute the orginal tensor to rearrange the axis or dimensions order 
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous Shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}")

Previous Shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


# Indexing (Selecting Data from Tensors)
Similar to indexing in Numpy

In [6]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [7]:
# Indexing on the zeroth dimension.
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
# Indexing on the first dimension.
x[0][0]

tensor([1, 2, 3])

In [10]:
# Indexing on the most inner bracket (last dimension).
x[0][0][0]

tensor(1)

In [13]:
x[:,1]

tensor([[4, 5, 6]])

In [14]:
x[:,1,1]

tensor([5])

In [15]:
x[:,:,2]

tensor([[3, 6, 9]])

In [16]:
x[:,:,0]

tensor([[1, 4, 7]])

In [17]:
x[:,1,:]

tensor([[4, 5, 6]])

In [18]:
x[:,1,1], x[0][1][1]

(tensor([5]), tensor(5))

In [20]:
x[:,2,2], x[:,:,2]

(tensor([9]), tensor([[3, 6, 9]]))

## Pytorch and Numpy

In [9]:
import torch
import numpy as np

array = np.arange(0., 10.)

tensor = torch.from_numpy(array) 
# Note: When converting from numpy to torch, Pytorch reflects the default data type in numpy which is float64.
# Unless specified otherwise,
tensor32 = torch.from_numpy(array).type(torch.float32)
array, tensor, tensor32, tensor32.dtype

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.float32)

In [10]:
array = array + 1
array, tensor

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [14]:
tensor = torch.ones(7)
array = tensor.numpy()
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [15]:
tensor = tensor + 1
array, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))